### PR TITLE
chore: add dependency array for useAnimatedStyle

### PR DESCRIPTION
**Pull request by imWildCat**
## Summary

Adds the dependency array of `useAnimatedStyle`

This helps custom bundler for react native web like `vite`.

## Test plan

running examples

image

### CODE REVIEW

**Comment by gunnartorfis** [comment]
Thanks for the PR!

I have been thinking a bit about the web part. What do you think about having an index.web.ts file with a `export * from 'sonner' `?

**Comment by imWildCat** [comment]
> Thanks for the PR!
> 
> I have been thinking a bit about the web part. What do you think about having an index.web.ts file with a `export * from 'sonner' `?

TBH, I'm not an expert for this. 
If this one-liner is acceptable, let's move forward first.

**Comment by imWildCat** [comment]
thanks @gunnartorfis !

going to integrate this great lib into my infoflow.app!

**Comment by gunnartorfis** [comment]
Awesome! I've just released 0.10.1 which includes this fix.

**Pull request merged**
