### PR TITLE
fix: custom jsx component breaks animation

### PR DESCRIPTION
**Pull request by mrpmohiburrahman**
## Summary

Fixes: https://github.com/gunnartorfis/sonner-native/issues/151

## Test plan

No special setup required.
Updated the custom JSX component in ToastDemo.tsx of the example app to align components centrally for the "Custom JSX" button.

### CODE REVIEW

**Review by gunnartorfis — CHANGES_REQUESTED** [review]
Sorry for the late review. 

In order to minimize the diff and keep changes to a minimum, could you keep the if (jsx) { return .. } above the main return? You'll need to render the <ToastSwipeHandler> there too in that case. You can create a memoized object to reuse it for the both usages of the ToastSwipeHandler. 

Let me know if I should take over this PR or if you want to continue to work on it.

**Comment by mrpmohiburrahman** [comment]
> Let me know if I should take over this PR or if you want to continue to work on it.

I am working on it, give me some time.

**Comment by mrpmohiburrahman** [comment]
> could you keep the if (jsx) { return .. } above the main return? You'll need to render the there too in that case. 

What I am understanding is if we put `if (jsx) {return ...}` there would also be another` ToastSwipeHandler` for that if block.

> You can create a memoized object to reuse it for the both usages of the ToastSwipeHandler.

And I should create memorized object for ToastSwipeHandler like the following so it can be used on both render function ( on `if block` and other is outer render function )

<details>
  <summary>Click to expand code snippet</summary>

```
    const toastSwipeHandlerProps = React.useMemo(() => ({
      onRemove: () => {
        onDismiss?.(id);
      },
      onBegin: () => {
        isDragging.current = true;
      },
      onFinalize: () => {
        isDragging.current = false;
        const timeElapsed = Date.now() - timerStart.current!;

        if (timeElapsed < duration) {
          timer.current = setTimeout(() => {
            onDismiss?.(id);
          }, duration - timeElapsed);
        } else {
          onDismiss?.(id);
        }
      },
      onPress: () => onPress?.(),
      enabled: !promiseOptions && dismissible,
      style: [toastContainerStyleCtx, styles?.toastContainer],
      className: cn(
        classNamesCtx?.toastContainer,
        classNames?.toastContainer
      ),
      unstyled,
      important,
      position,
    }), [
      onDismiss,
      id,
      duration,
      dismissible,
      promiseOptions,
      onPress,
      toastContainerStyleCtx,
      styles?.toastContainer,
      classNamesCtx?.toastContainer,
      classNames?.toastContainer,
      unstyled,
      important,
      position,
      cn,
    ]);
```
</details>

is this ok ?

**Comment by gunnartorfis** [comment]
Yes, that looks good

**Comment by mrpmohiburrahman** [comment]
@gunnartorfis , Please, check my latest commit.

**Review by gunnartorfis — APPROVED** [review]

**Pull request merged**
